### ISSUE TITLE
remote server bootstrap-sass pre-compilation failed

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#103]
one approach is just to use development and skip assets pre-compilation

another way is to use bootstrap css instead of sass

**Comment by franklingu** [comment]
[bootstrap-sass issue](https://github.com/anjlab/bootstrap-rails/issues/91)

[related stackoverflow Q](http://stackoverflow.com/questions/21911620/rails-bootstrap-sass-assets-compilation-error-undefined-variable-alert-padding)

**Comment by franklingu** [comment]
stopped pre-compilation for scss files solved the problem. however, this issue deserves more insights rather than just making it work. i will downgrade the priority instead

**Comment by CFRG16** [comment]
Did anyone figure out how to solve this problem. I've tried precompiling and not precompliling, Ive tried removing wildcards and specifically referencing every file. Nothing is working.

**Comment by franklingu** [comment]
maybe you can ask in https://github.com/twbs/bootstrap-sass here? @CFRG16
