### ISSUE TITLE
setup ssl for the server for security reasons

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#113]

**Comment by franklingu** [comment]
https://www.globalsign.com/en/ssl/ssl-open-source/

**Comment by franklingu** [comment]
related to #144

**Comment by J0** [comment]
I would like to to take this issue.

**Comment by J0** [comment]
Prof @zhaojin42 I am intending to take quite a few of the issues which are related to the server. Is there any way can I get access to the server?
