### ISSUE TITLE
create a evaluation form for evaluation and save form for viewing

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#114]

**Comment by franklingu** [comment]
well, html form's values have to stored separately.
we can just store all the values for now and use js to dynamically fill them in.
or if I have 2 weeks, I will use question system instead: anyway we only have 2 types of questions so far

@knmnyn

**Comment by knmnyn** [comment]
Ok then use the question form.

On Sunday, May 10, 2015, franklingu <notifications@github.com> wrote:

> well, html form's values have to stored separately.
> we can just store all the values for now and use js to dynamically fill
> them in.
> or if I have 2 weeks, I will use question system instead: anyway we only
> have 2 types of questions so far
>
> @knmnyn <https://github.com/knmnyn>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nusskylab/nusskylab/issues/114#issuecomment-100655972>
> .
>


-- 
Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
I think I will go with "storing form values and load it to the html form using js" approach. will be at least delivered by the end of this week
