### ISSUE TITLE
research on APIs for rails and prepare for API + angular/ember structure

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#119]

**Comment by knmnyn** [comment]
Do you really need to go this direction now?  What's the reason to migrate towards a 1 page app with JS MV* support?

https://www.airpair.com/ruby-on-rails/posts/ember-vs-angular-with-rails

**Comment by franklingu** [comment]
for consideration. that is why i did not put any label to this issue.

for simplicity of development in a sense, sever will just provide api service

**Comment by knmnyn** [comment]
oh, ok.  Got it.
