### ISSUE TITLE
adviser edit link not showing for advisers

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#125]

**Comment by franklingu** [comment]
I need du's confirmation that he can still login to the system. cause previously @knmnyn added him twice as an adviser&user(the second time used A instead of lower a). i changed it manually in the system already.

**Comment by franklingu** [comment]
i will do conversion to lower case for now before validation

**Comment by knmnyn** [comment]
Hi Franklin:

Will you want to meet online this evening after 10:30pm?

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
