### ISSUE TITLE
Get updated list of students ingested into Skylab

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#135]
Some of them may not have matric numbers inside as they were manually inserted without filling in their matric numbers.

**Comment by knmnyn** [comment]
Asking students who are missing to try again.

**Comment by franklingu** [comment]
sorry. the error was caused by my overlooking of the fact that if primary email addr is same as nus email address, the text is "My NUS email is my primary email account". for those students, I will be using NUS email as email for user then
