### ISSUE TITLE
enable team to view own submission to previous milestone for reference

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#138]
You can try to add some template sections from this post on Piazza.

**Comment by franklingu** [comment]
@knmnyn, sorry i forgot to mention to you that I tried the link last week but access denied. can you just send the template to me?

**Comment by franklingu** [comment]
@knmnyn would it be convenient for you to email me direct the template. I tried the link last time. did not work: blocked

**Comment by knmnyn** [comment]
Sorry, this is obviously too late because students have already finished
the first milestone.

For the second milestone, perhaps you should add a button to allow them to
copy-paste their first milestone's project log and README into the current
empty text box.  Perhaps make separate buttons for the README and one for
the project log.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
this will be most likely not be available for this milestone. the change involved is bigger than I previous expected. as a walk around, user can just view all submissions. I will add that link to submission creation page for temporary solution
