### ISSUE TITLE
devise + omniauth does not work on ruby 2.2 and rails 4.2

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#14]
seems some discussions are here https://github.com/plataformatec/devise/issues/2692

and since this is expected to be really tricky, we will just open a new branch for solving this later

**Comment by Leventhan** [comment]
Hmm. That's strange. I have a working Omniauth + Devise setup for a personal project [SheetHub](http://sheethub.co/) but I think I didn't use rails engines here.

**Comment by franklingu** [comment]
the problem is not engines. anyway, when I was setting up the project, i experienced similar error
