### ISSUE TITLE
Nothing seen when login to sky lab

### ISSUE THREAD

**Issue by tangwr** [nusskylab/nusskylab#143]

**Comment by franklingu** [comment]
can you provide more details to this issue?

**Comment by franklingu** [comment]
it is okay. I figured it out. but next attaching screenshot or something similar would be the best

**Comment by franklingu** [comment]
well, we do not have a log for all actions yet but most likely your account has been modified cause your email has been changed. your setting is fine in my local server too.

really sorry for this.
