### ISSUE TITLE
Unable to see my team member's name

### ISSUE THREAD

**Issue by harishv7** [nusskylab/nusskylab#148]
Hi, currently me and my team member are able to login separately successfully. However, when we login, we can only see our own names under the team information. My name is Venkatesan Harish and my partner's name is Alvian Prasetya. Team name is The Digital Catalyst.

Thanks for the assistance.

**Comment by franklingu** [comment]
adjustment done.

and this is caused duplicate sign-up: you and your partner signed up twice as a team. and the team names in the 2 sign-ups are not the same
