### ISSUE TITLE
Unable to upload new images with tiny mce editor 

### ISSUE THREAD

**Issue by harishv7** [nusskylab/nusskylab#152]
When I click on insert images, I am unable to upload a local copy of the image on my computer.

**Comment by franklingu** [comment]
support for image uploading is not planned so far. this will be considered as new feature for later release

**Comment by knmnyn** [comment]
You can insert images to hosted files.  For example currently you can separately upload images to Dropbox and share the public link to your README or Project Log documentation.

**Comment by harishv7** [comment]
Since some people have mentioned that Dropbox is not available for access in China, I have separately hosted my images at imgur.com and provided the link in the README and Project log.

Thank you for the kind reply and assistance.

Regards,
V.Harish
