### ISSUE TITLE
Unable to reset password.

### ISSUE THREAD

**Issue by vradical** [nusskylab/nusskylab#153]
There seem to be some problem with the password reset for me. Every time i key in the new password, it just state "Please review the problems below:" without giving me any other error message. I have tried resetting my password multiple times to make sure i type correctly but it doesnt help. When I purposely do the wrong things (e.g short pw, leave blank), the error message are displayed correctly.

**Comment by vradical** [comment]
![image](https://cloud.githubusercontent.com/assets/8266047/7902224/8a8803e4-07e4-11e5-8b05-de31579460df.png)

**Comment by franklingu** [comment]
thanks for your testing. Honestly this part is handled by a gem which I just picked up. However, it seems that you are the only person so far who encountered this problem.

I tested myself. working. one guess is that the reset token is invalid after some time. try re-send?

**Comment by vradical** [comment]
All the above test are done within 1 min after i receive the mail. Anyway, i tried again today for the password reset and it works. Thanks for the help!
