### ISSUE TITLE
No team assigned

### ISSUE THREAD

**Issue by ladadeedum** [nusskylab/nusskylab#155]
When logged in (using nusnet id), i'm displayed as users/ID

Isaac - users/135
Nicholas - users/190

**Comment by franklingu** [comment]
I do not know why the two User IDs you are providing are both invalid. but anyway, I figured out who Nicholas is in the system and adjusted for him. As for Issac. OK now too

**Comment by ladadeedum** [comment]
My user ID changed to 429, when i login to skylab, the url i get is
http://nusskylab-mht7cvdwt2.elasticbeanstalk.com/users/429

Still no roles or teams though

**Comment by franklingu** [comment]
Please check now. either you or your partner provided wrong matric number during sign up

**Comment by ladadeedum** [comment]
Working great now - Thank you so much!

**Comment by franklingu** [comment]
Welcome :P
