### ISSUE TITLE
Evaluatings -- Evaluator evaluating relationship should be unique

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#156]
We need to have multiple teams being evaluated by a single team.

I tried to enter three teams to be evaluated by the same team but it throws this error.

**Comment by franklingu** [comment]
can you add the screenshots or something? cause I do not why the constraint is working against the situation

**Comment by franklingu** [comment]
by the way, I am adding select2 support for select fields now. will deploy by tomorrow noon

**Comment by knmnyn** [comment]
I can assign multiple teams to evaluate a team but cannot assign a team to evaluate multiple target teams

- Min (from mobile)

**Comment by knmnyn** [comment]
![screen shot 2015-05-31 at 11 40 53 pm](https://cloud.githubusercontent.com/assets/217067/7904052/86a59de0-07ee-11e5-8567-67ada7dafd44.png)

**Comment by franklingu** [comment]
yes. my bad. I forgot to put scope to uniqueness constraint although I did mean to

**Comment by franklingu** [comment]
I added that evaluating relationship. are you manually adding all those relationships? in which order? I mean I can do reverse order and help you upload those data
