### ISSUE TITLE
Nothing after login

### ISSUE THREAD

**Issue by chanshihui** [nusskylab/nusskylab#158]
Hi,

After I logged into skylab, there's no option for me to upload my README or anything.

Thankyou

**Comment by franklingu** [comment]
what is your name in the system/what is your team name?

**Comment by chanshihui** [comment]
Chan Shi Hui
Team: Orange

**Comment by franklingu** [comment]
please check now. note that if you want to use pswd to login, you need to use NUS email instead of hotmail. i just deleted the duplicated account--signed up with hotmail

**Comment by chanshihui** [comment]
thankyou!
