### ISSUE TITLE
No access control on different pages?

### ISSUE THREAD

**Issue by Gisonrg** [nusskylab/nusskylab#160]
Is there any access control on different page?
http://nusskylab-mht7cvdwt2.elasticbeanstalk.com/advisers/xxx
http://nusskylab-mht7cvdwt2.elasticbeanstalk.com/teams/xxx

I could replace xxx with other number so that I can visit other advisers' and teams' page and manipulate their evaluation and submission.

**Comment by franklingu** [comment]
users related, students related pages are fully protected by access control already. others are in schedule
