### ISSUE TITLE
add custom action for importing evaluating relations from csv

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#161]

**Comment by knmnyn** [comment]
Very nice!


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
Quite some relations are there. Now I am asking all advisers to check team
names for those changed names and change the spreadsheet accordingly so
that import will be more successful
