### ISSUE TITLE
Still unable to evaluate other teams

### ISSUE THREAD

**Issue by tangwr** [nusskylab/nusskylab#171]
I submitted this issue yesterday but the thread was closed and I still can't evaluate other teams.
FYI we change our team name. I did not include the new team name in yesterday post.

Team Name: Psy-Code
Team Number: 125
A0125531R Tang Wei Ren 
A0133267H Muhammad Razali Bin Sa Mohd Yacob

**Comment by franklingu** [comment]
so sorry. I did remember I changed for your team. but somehow things were still not fine.

so sorry about this
