### ISSUE TITLE
User navigation: redundant home button

### ISSUE THREAD

**Issue by madsonic** [nusskylab/nusskylab#179]
The home button only leads you back to your current page other than when you are on the landing page of skylab. User would not be able to navigate around the site without having to type in the URL themselves, assuming that they know what the URL is.

**Comment by franklingu** [comment]
then what is your suggestion for home link?

**Comment by franklingu** [comment]
closed due to inactivity

**Comment by Sunxperous** [comment]
The home button should direct the user to the page which is shown right after they log in, e.g. adviser page for advisers. This allows for consistent and predictable behaviour.

**Comment by franklingu** [comment]
OK. accepted. Will rethink about it
