### ISSUE TITLE
Students can view private evaluations

### ISSUE THREAD

**Issue by wryyl** [nusskylab/nusskylab#182]
URL: `http://nusskylab-mht7cvdwt2.elasticbeanstalk.com/milestones/1/teams/:id/received_evals`

**Steps to reproduce:**
- From the student page, click on `Submit Feedback`, then `View evaluations`.
- Click on the `Private` tab

**Problem:** All evaluations are available for the student to access, including private ones. Students can view the critical feedback as well as the overall evaluation score given.

**Expected:** The private tab should not be available for students to view.

**Comment by franklingu** [comment]
Teams' or advisers' names are hidden, which makes this issue invalid

**Comment by wryyl** [comment]
Fair enough, however the Overall Evaluation description states that

> Private: Overall Evaluation (Section 5 of 5)
> This section will only be viewed by the advisors and not by the target group. 
> This section is for the adviser's and faciltator's reference only. 

which leads me to believe that students being able to view the score given is unintended.

Feel free to close the issue if this is intended behavior.

**Comment by franklingu** [comment]
that is okay. thanks for your suggestion anyway.
for that instruction, that is legacy--instruction from last year
