### ISSUE TITLE
adding image uploading feature to submission rich text

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#187]

**Comment by franklingu** [comment]
http://api.imgur.com/ personally I will recommend services like this to solve this issue @knmnyn

**Comment by franklingu** [comment]
so now I will most likely go with image upload using imgur api. there are plug-ins to tinymce but I will be creating another button to upload image and get back the upload image link for use to copy and use

**Comment by knmnyn** [comment]
Ok.  Sounds fine.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
just tested with imgur. sometimes the server will respond with "Imgur is over capacity" and after a while the uploading will be fine again. that is a problem though

**Comment by knmnyn** [comment]
Should be ok.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
