### ISSUE TITLE
"View evaluations" for milestone 2 displays milestone 1's form

### ISSUE THREAD

**Issue by ladadeedum** [nusskylab/nusskylab#196]

**Comment by franklingu** [comment]
can you provide information/details like pictures? I tested--meaning that I logged as one student and see no problem

**Comment by ladadeedum** [comment]
![capture](https://cloud.githubusercontent.com/assets/8996422/8525727/2005066c-2435-11e5-9573-2aa6584e4b16.PNG) I think this evaluation form is the one from milestone 1? There is no acceptance testing part

**Comment by franklingu** [comment]
accepted. locally the display is fine. need to figure out

**Comment by franklingu** [comment]
OK. some commits have not be pushed to aws. btw, with new commits which include control of deadline, viewing of peer evaluations from received_evals will only be available after evaluation deadline
