### ISSUE TITLE
Rework UI of the view peer evaluation

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#200]
Factor into:

Peer Teams {1-3}
Adviser
Anonymized Critical Feedback

**Comment by Sunxperous** [comment]
Individual peer evaluations should also contain the names of the person/group evaluating and being evaluated. Currently it only shows "Peer Evaluation" where the only available reference is the team id on the url.

**Comment by franklingu** [comment]
@Sunxperous not sure if I get it but the table in students page does contain who is the evaluator team

**Comment by Sunxperous** [comment]
Sorry, to clarify, I am talking about viewing a single peer evaluation page, for e.g. http://nusskylab-mht7cvdwt2.elasticbeanstalk.com/teams/1026/peer_evaluations/19
