### ISSUE TITLE
Team scores that need to be calculated and shown on the team page

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#201]
1. The average score over all three milestones for all teams for the overall project score.

Teams that evaluated target team.
EM1. A B C
EM2. D E F
EM3. D H I 

OverallProjectScore after EM1: (A + B + C ) / 3
OverallProjectScore after EM2: (A + B + C + D.EM2 + E + F ) / 6
OverallProjectScore after EM3: (A + B + C + D.EM2 + E + F + D.EM3 + H + I ) / 9

2. The average score over all peer feedbacks

Teams that the target team evaluated.
EM1. 1 2 3
EM2. 4 5 6 
EM3. 4 7 8

OverallFeedbackScore after EM3: (1 + 2 + 3 + (4 x 2) + 5 + 6 + 7 + 8) / 9

**Comment by franklingu** [comment]
@knmnyn , it is OK to list average ratings for each milestone--not the overall
and adviser's rating included or not?

for now, I am listing average scores for each milestone and adviser's rating is not included. if changes are demanded, simple open another issue with ref to this thread. thanks :)

**Comment by knmnyn** [comment]
Yes, both are needed, but the most important is the single average.

Advisers' feedback is included.  If possible (no worries if too difficult) use the advisors' rating as a cohort setting (n=2) Nx the weight of the normal peer weighting.

E.g., in above scenario 1 (since for scenario 2, it doesn't have any effect):

Teams that evaluated target team.
EM1. A B C
EM2. D E F
EM3. D H I
Advisor J evaluates the team as well.

OverallProjectScore after EM1: (A + B + C + J.EM1 + J.EM1) / 5
OverallProjectScore after EM2: (A + B + C + D.EM2 + E + F + J.EM1 + J.EM1 + J.EM2 + J.EM2 ) / 10
OverallProjectScore after EM3: (A + B + C + D.EM2 + E + F + D.EM3 + H + I + J.EM1 + J.EM1 + J.EM2 + J.EM2 + J.EM3 + J.EM3) / 15
