### ISSUE TITLE
S/N for index views

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#209]
Sometimes it's helpful to just have a column to mark row number.  Can you add this?

**Comment by franklingu** [comment]
? while, which tables you are referring to ?

**Comment by knmnyn** [comment]
Any.  Specifically in the admin view, the list of teams and students.

**Comment by knmnyn** [comment]
Just add row numbering to the view.  Nothing in the model.  Just easier to take counts and sums with them.

**Comment by franklingu** [comment]
if you just want counts, I suggest use JS to count and specify it somewhere instead of rendering of all indexes. let's say after sorting then indexes should be out of sort then

**Comment by knmnyn** [comment]
That's fine too.
