### ISSUE TITLE
Milestone # should be on the top of each submission viewing page

### ISSUE THREAD

**Issue by Sunxperous** [nusskylab/nusskylab#221]
At the same time, any additional fields which are short, such as the video link, can be placed on top as well beside the milestone # on a single line.

This will make it clearer as compared to having the two abovementioned two fields at the end of the page.

**Comment by franklingu** [comment]
thanks for your suggestion but when the semester starts, milestone will not be a form field any more

**Comment by Sunxperous** [comment]
What has this got to do with the semester starting? Just to clarify, I meant viewing of each submission, not posting. Thanks.

**Comment by franklingu** [comment]
edited. will consider
