### ISSUE TITLE
setting soc VM server up with rbenv and serve to public

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#244]
prepare to shut down the AWS server

**Comment by franklingu** [comment]
it is running locally only, but cannot be accessed from other machines @knmnyn is it because there is no sub domain allocated to this VM? nusskylab-dev-i.comp.nus.edu.sg

**Comment by knmnyn** [comment]
No, it's because you need to apply in eforms to have your vm accessible
from the outside.

Don't take down the Amazon instance for at least a week more. We are using
data inside it and the data is still going to change.



Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
I actually wrote email regarding this matter to tech service but no response yet.
Should I resubmit a form or asking for access outside for this instance?

OK. But the server that is running now in VM or my local disk has all the data from current AWS server. in theory it does not matter even if we switch

**Comment by knmnyn** [comment]
Noted.

For the form submission, if you wait 1-2 days, and it doesn't show let me know.
Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of
Singapore :: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
@knmnyn prof, the server is up and running at http://nusskylab-dev.comp.nus.edu.sg/.
There is not auto deployment script so far. Right now what I do is git pull & puma -e production. Later I will write a script for auto pulling from master and run any pending migrations and redeploy with puma.

it is httpd + puma now. Will mostly stick to this until I plan to explore more on server performance tuning

**Comment by franklingu** [comment]
One thing really annoying, seems that every time I want to use ruby related commands I have to reload current bash_profile--it does not automatically do it for some reason

**Comment by franklingu** [comment]
by the way, the original AWS server has been taken down

**Comment by knmnyn** [comment]
Noted.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by knmnyn** [comment]
http://nusskylab-dev-i.comp.nus.edu.sg/auth/NUS

Fails.  Can't see anything.

Please fix.  Don't take down AWS unless you can verify that things are working.
Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of
Singapore :: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
Well, I just tried. It was working yesterday when I tested--but that was when I was still su to the VM. After I exited, I did not try it again. The problem is that once I exit, there is no "shell" available anymore for log to log its content. therefore logging throw an error
(I spawned the server process from bash terminal in bg. It pipes some logging content back to shell--but when I exit ssh, parent process is gone. and logging will just fail)

Currently it is fine--I am working inside. However, I can only thoroughly fix the issue when I am back

**Comment by franklingu** [comment]
BTW, use http://nusskylab-dev.comp.nus.edu.sg/ instead

**Comment by knmnyn** [comment]
Ok, got it.  Thanks!  Was able to login.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of
Singapore :: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
Sorry about this. But just now when I tried clearly I still did not solve the issue: when my ssh session is finished, errcon will still happen. I need to dig more into this

so if you are not in a hurry, please check the server tmr. but in the meanwhile, I will just keep my ssh open.

Again, really sorry for this :( that I cannot work it right now. Will get back to you ASA I am work and fix it

**Comment by knmnyn** [comment]
Ok, got it.  I will need to access it this afternoon, so please help
maintain access, if possible.
Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of
Singapore :: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
