### ISSUE TITLE
upload code to remote server(deployment)

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#26]

**Comment by Leventhan** [comment]
You can definitely use [paperclip](https://github.com/carrierwaveuploader/carrierwave) and AWS S3 to store files like this.

**Comment by franklingu** [comment]
well, I have not really start on this yet. possibly we will just use vagrant image for production

**Comment by Leventhan** [comment]
Oh wait, this is for the Rails code? Nvm, I thought the students have to upload code or smth.

**Comment by franklingu** [comment]
http://nusskylab-mht7cvdwt2.elasticbeanstalk.com/

puma + nginx for server

however, there is an urgent issue with bootstrap-sass mentioned in #103 . need to fix this now

**Comment by knmnyn** [comment]
Probably don't want to leave naked development URLs in issues or commit mentions.
