### ISSUE TITLE
add the notion of notes to the system

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#27]
a possible way: an integer as ref, string for type, for generality on all kinds of entities

**Comment by Leventhan** [comment]
What's the relationship between notes and other entities? What is it used for, as comments from evaluators? It's achievable with [polymorphic associations](http://guides.rubyonrails.org/association_basics.html#polymorphic-associations) but if it's for discussion stuff It's probably better to have a commenting system with [acts_as_commentable](https://github.com/jackdempsey/acts_as_commentable)

**Comment by knmnyn** [comment]
acts as commentable or its equivalent is probably a good idea here.
All model instances may potentially need to receive comments.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
noted.
