### ISSUE TITLE
Cannot create a new user

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#277]
When trying to create a mentor, I could only pick from existing users (probably ok).
But I then logged out but could not create a new user, only try to login or use the forget password option.

Help?

**Comment by franklingu** [comment]
Well, creating mentor directly is disabled. In fact, they will not come
back.  Creating user with role will be added later.

**Comment by franklingu** [comment]
And I did not get the log out part. But forget password is not enabled for
now. After taking down from aws I left it that way. Will fix as you
requested

**Comment by franklingu** [comment]
This will most likely be closed as it is not error with creating user but redirection after user's creation to user's page will result in error. linked to #278 . Also need to enable sendgrid for email purpose.

**Comment by franklingu** [comment]
see #280 for mailing issue.
when admin creates a user now, a random pswd will be generated but the user does not know. Will work on this

**Comment by franklingu** [comment]
you are right. this was a bug with my code. params are strings but it requires int
