### ISSUE TITLE
Home for admin goes to /users/160 that results in rails error

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#278]
Seems to happen in most views

**Comment by franklingu** [comment]
I do think you have brought this issue right? Not the same one? What are
the urls?

**Comment by franklingu** [comment]
This was because I removed one method in Users but view is still using it. sigh, regression error again. really sorry about this

**Comment by franklingu** [comment]
you are right. currently no matter which user page you go to, it is basically an error

**Comment by franklingu** [comment]
if you are asking why when you press home link, you get redirected to users/160--that was because you have multiple roles.
