### ISSUE TITLE
add the notion of cohort to the system

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#28]
for now, we can just attach an integer field saying which year it is

**Comment by franklingu** [comment]
actually this seems not that trivial, cause not just roles but also teams, milestones...evaluations are linked to cohort too

**Comment by franklingu** [comment]
@knmnyn

**Comment by Leventhan** [comment]
You can probably use ActiveRecord [enums](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html) for this.

**Comment by franklingu** [comment]
okay. agreed. but what I am saying is that it seems that many entities need this attribute. but notice that I assigned p.low--priority low @Leventhan

**Comment by Leventhan** [comment]
Ah I see, then I think you can look into having an ActiveRecord [concern](http://api.rubyonrails.org/classes/ActiveSupport/Concern.html) (module mixin) for use in entities that need this attribute. You can also define a before_create [callback](http://guides.rubyonrails.org/active_record_callbacks.html) to make sure that when entities are created, the cohort attribute is set automatically.
