### ISSUE TITLE
Add a space between @ [Team Name] in Student View

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#294]
Also change @ to " of "

**Comment by franklingu** [comment]
I think the " of " does not look good
![students-screenshot](https://cloud.githubusercontent.com/assets/4099698/10508965/b5a7b414-735c-11e5-8406-9b076afa2ae6.png)

**Comment by knmnyn** [comment]
Ok.  Then find another way.  Maybe:

Student (Team)?

Student (member of Team)?

Student / Team?

The "@" doesn't work for me because of the social media convention of @ denoting a mention of an individual.  It'd be ok on a team page where something like "Team (@Student A @Student B)" was present.
