### ISSUE TITLE
User information should allow a text description and a few profile links.

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#295]
Under user information.

Allow a self-edit text area for description.
Allow edit of a few text fields for URLs for their webpage, Github ID, LinkedIn, Facebook profile.
Place suitable instructions for these to say that this information will appear on the public portion of their page if checked, otherwise will only be visible to logged in users of Skylab.

**Comment by franklingu** [comment]
this issue is done. as for user's public profiles, it is in #307
