### ISSUE TITLE
Create New User screen: mailing

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#298]
Please add useful instructions on how to add a user (trying to add users to create mentors).

Even if I choose provider_nil, I don't know what to fill for uid (actually it should be UID).

Does it send an email to the listed email address after user creation?

**Comment by franklingu** [comment]
I will work on this and feedback to you late regarding this issue.
But answers for questions above based on current code base:
Provider_nil is legacy--at first and so far provider is required for openid, so either NUS or nil. Currently not email sent yet, as mailer is not started yet.

**Comment by franklingu** [comment]
linked to #236
