### ISSUE TITLE
team entities may become floating. can use a routine checking to remove those that are referenced by any students

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#32]

**Comment by franklingu** [comment]
can also do clean up after editing of students

**Comment by Leventhan** [comment]
How can team entities be floating? Can you just prevent it totally?
If you absolutely need routine sweepers, check out [clockwork](https://github.com/tomykaira/clockwork).

**Comment by franklingu** [comment]
well, the plan now is to delete old team entities at the point of creating new team for students. and this issue is more complex as currently the logic for creating/updating team entities is not user friendly. but since this is for admin only, we will postpone this issue

**Comment by Leventhan** [comment]
I'm still not sure of the details, but you can look into [`dependent: :destroy`](http://guides.rubyonrails.org/association_basics.html). Objects will also be destroyed if they're associated with `dependent: :destroy`.

**Comment by franklingu** [comment]
this will be moved to later stages as it is dependent on UX design for admin side

**Comment by franklingu** [comment]
wait for #116

**Comment by franklingu** [comment]
an example of #251
