### ISSUE TITLE
create staff view

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#328]
- [ ] staff  view
- [ ] tutor role
- [ ] facilitator role

**Comment by knmnyn** [comment]
Stuff view? :-S

**Comment by franklingu** [comment]
why? @knmnyn

**Comment by knmnyn** [comment]
What is a "stuff" view?  Can you make it more specific?

**Comment by franklingu** [comment]
http://orbital.comp.nus.edu.sg/?page_id=1438

Like this?

**Comment by knmnyn** [comment]
Ooooh.

Staff, not stuff.  I get it.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
I did not realize that until just now
