### ISSUE TITLE
Create a list of default tags for registration

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#330]

**Comment by franklingu** [comment]
@knmnyn , maybe we can just list here under this issue and later I will add it to DB

**Comment by knmnyn** [comment]
Ok, that's fine.

Here we go.  You could group them, either by giving a prefix (e.g.,
"lang:") or similar.  Or I can add an explanation in the description text.

= Language
python
ruby
c
java
javascript
csharp
swift

= Web framework
rails
django
gae
nodejs
angularjs
reactjs
emberjs
flask
php
meteor

= Phone platform
ios
droid

= IDE
vim
emacs
eclipse
pycharm
idle
nitrous
cloud9

= eCommerce
paypal
ecommerce
square
braintree
square

= Cloud
azure
ec2
docker
vmware
digitalocean
socvm

= purpose
fun
gamedev
devops
webapp
game
nusmods
dating
infosec
analytics
eca
cca
volunteer
studentclub
market
contests
hackathon
showcase
blk71
nushackers
acm
nussu
compclub
gdg
greyhats

= Embedded Systems
raspberrypi
arduino
iot

= Game Frameworks
gamepress
unity
gamemaker
corona
stencyl
gamesalad
pygame

= cms
wordpress
joomla
drupal

= audience
nus
university
youths
adults
elderly
children
toddlers
families
parents




Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
