### ISSUE TITLE
Implement team invitation feature

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#332]
1. can select from a list of pending students without a team or team invitation
2. the other one will either accept or reject
3. when accept, the team is no longer pending(but students are still pending?)
4. when reject, free to be selected by others or select others

**Comment by knmnyn** [comment]
Yes, to #3

On Sunday, 31 January 2016, franklingu <notifications@github.com> wrote:

>
>    1. can select from a list of pending students without a team or team
>    invitation
>    2. the other one will either accept or reject
>    3. when accept, the team is no longer pending(but students are still
>    pending?)
>    4. when reject, free to be selected by others or select others
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nusskylab/nusskylab/issues/332>.
>


-- 
Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
