### ISSUE TITLE
use locals over instance viariables

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#34]
a link http://thepugautomatic.com/2013/05/locals/

**Comment by Leventhan** [comment]
I don't think there's a strong argument for using locals over instance variables.

**Comment by franklingu** [comment]
yes. it is not compulsory to do this and to other people it may not seem a best practice. but I am currently sharing some partials and using locals seems more reusable. 

and it is always open for discussion

**Comment by franklingu** [comment]
this will be closed as it is not necessary to fix all of the existing ones now
