### ISSUE TITLE
Add a view for users that are not assigned any other roles.

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#363]
Could also add an action to assign user to a role for this cohort.

**Comment by franklingu** [comment]
? not really sure about what you mean. maybe we can discuss this in person

**Comment by knmnyn** [comment]
For users that have been registered but not assigned any status, e.g.,
current student, mentor, adviser, etc.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
