### ISSUE TITLE
email address filter doesn't work properly for some newer TLDs

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#384]
We have a mentor with an email address ending in @...solutions, which is a valid TLD.

Can you check whether the email filter can be set less restrictively?

**Comment by franklingu** [comment]
which one? it is in fact just the regex written by myself and exceptions may happen

**Comment by knmnyn** [comment]
There's one for .solutions.  Strange TLD to me but one of our mentors has
their primary email with this TLD.




Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
which one is that? I searched both cohorts but did not find it

**Comment by knmnyn** [comment]
Hi:

That's exactly the point.  I cannot add the user because the email address
is considered invalid and doesn't pass the validation step in user account
creation.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
then I have completely understood you. thought you were talking about existing users
