### ISSUE TITLE
current implementation of idf is not right

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#385]
currently it is counting terms frequency. but instead, it should consider documents frequency.

since we are talking about change, just align it with logarithm calculation of quotients as well.

**Comment by knmnyn** [comment]
Should be ok, since your tags can only appear once per document anyways, so document frequency is the same as collection frequency.

**Comment by franklingu** [comment]
I got your point now but previously I did not get it and I did not get the algorithm. The N I am using is number of tags in the database-- but it should be number of students.

**Comment by knmnyn** [comment]
Yes, that's right -- your documents are the "students" or more generally, anyone who fills out the survey.

**Comment by franklingu** [comment]
I was wrong. I used number of students' registration responses, which is OK. and since we brought this up already, I will refactor the method to for general matching. And I will change it to log based as well

**Comment by franklingu** [comment]
one question though:
https://en.wikipedia.org/wiki/Tf%E2%80%93idf#Inverse_document_frequency_2

when it is saying log, what is the base? base 2?
