### ISSUE TITLE
Staff views should have #anchors for different parts of the page

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#386]
Such that an external #href can jump directly to that section.

E.g., http://nusskylab-dev.comp.nus.edu.sg/public_views/public_staff?cohort=2015#mentors

or similar

**Comment by knmnyn** [comment]
Should (I think) be pretty easy to do, by adding an appropriate <A NAME> tag at the header of each section.

**Comment by franklingu** [comment]
do we need a mini map of page as well? not sure i expressed it clearly. like a vertical menu sort of thing

**Comment by knmnyn** [comment]
Sure, something like a fixed left or right menu, e.g., the fixed menu on
http://www.comp.nus.edu.sg/~kanmy/pubs.html#conf-2015



Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
