### ISSUE TITLE
Edit Team selection of mentors lists all mentors instead of mentors for the cohort only

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#389]
Probably need to check whether this is true for advisors too.

**Comment by franklingu** [comment]
Another legacy of cohort migration :P

**Comment by franklingu** [comment]
maybe it is better if we just show mentors in the student`s cohort. showing may not be a good idea

**Comment by franklingu** [comment]
I just checked the code, it is not showing mentors in current cohort only in fact. it is showing all now
