### ISSUE TITLE
Create new user results in bug

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#390]
We're sorry but something went wrong failure screen.

However, this does actually end up working.  The user gets created.

Better fix this and allow next actions to it.

**Comment by knmnyn** [comment]
Connected to #391

**Comment by franklingu** [comment]
maybe it is the mailer? I will check the log later

**Comment by franklingu** [comment]
it is the mailer;s bug. or not a bug in the code but a type in my production environmental variables settings--I got a variable`s name wrong for the mailer's settings
