### ISSUE TITLE
Allow editing of mentor to assign team from cohort.

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#392]

**Comment by franklingu** [comment]
can you be more specific?

you mean that in mentor's editing screen, we should editing of which **teams** are supposed to be supervised by this mentor?

**Comment by knmnyn** [comment]
Yes, allow the mentor to see which is the team that they are mentoring and
allow that to be changed by the admin role only.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
