### ISSUE TITLE
specify project environment setup via the use of setting files

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#4]
- [ ] vagrantfile
- [ ] gemlock(managed by gem, should not be a problem)
- [ ] jshintrc
- [ ] rspec

and more will be added as time goes

**Comment by Leventhan** [comment]
You'll also need a way to store credentials for external services (i.e. Github API Keys and AWS S3 credentials for file uploads) and not put it in version control. In Rails, it's [secrets.yml](http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml).

**Comment by franklingu** [comment]
yes. thanks for the reminder

**Comment by franklingu** [comment]
will be closed, no longer valid/important
