### ISSUE TITLE
integration with slack webhook or have chatting features/announcement system

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#40]

**Comment by Leventhan** [comment]
I think Slack integration is better here. It's as simple as making a POST to our slack webhook url. Really easy to set up: https://api.slack.com/incoming-webhooks

**Comment by knmnyn** [comment]
Agree with @yosriady.  Integration is pretty easy, and I set up the one for
our WP install (even though that code was a public WP plug-in that is a bit
broken).



Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
for sure integration is easier. but the worry here is that users have to use 2 systems if we keep relying on slack. if everything can be done in skylab, then users just need to bookmark one website :)
