### ISSUE TITLE
public view of user should list roles per cohort-year

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#407]
It'd be great if in the user public view (if allowed), a listing of all the roles per cohort were viewable.

e.g.
- Year X
  - Role 1
  - Role 2
- Year X-1
  - Role 3

**Comment by knmnyn** [comment]
For mentors it should list their mentored team.
For advisers it should list their advised team.

In projects, the listings should have hyperlinks to the person's profile if public.  

Actually, I don't see public profiles per person.  Were they there before?

**Comment by franklingu** [comment]
Nope. Have not implemented yet
