### ISSUE TITLE
team edit view does not keep previous level_of_achievement state.

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#410]

**Comment by franklingu** [comment]
Keeping a history? or logging in general?

**Comment by knmnyn** [comment]
No the edits don't stick.  I enter them into the system, and when I edit,
the values don't load and revert back to Vostok.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
