### ISSUE TITLE
team's edit: level_of_achivement does not get saved

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#412]
> No the edits don't stick.  I enter them into the system, and when I edit,
the values don't load and revert back to Vostok.

 by Min from #410

**Comment by franklingu** [comment]
![team_edit_1](https://cloud.githubusercontent.com/assets/4099698/14355104/693604ec-fd12-11e5-92a0-5bb58a333a24.png)
![team_edit2](https://cloud.githubusercontent.com/assets/4099698/14355111/6c6ad2b4-fd12-11e5-8563-fc8aa03c5f9b.png)

checked on local server. seems not problem @knmnyn

**Comment by knmnyn** [comment]
There was one screen where it doesn't stick but I forget which one.  If I
see it again we can reopen the issue.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
Closed due to inactivity.
