### ISSUE TITLE
sendgrid mailer's cc to self doesn't list to whom the emails were sent.

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#413]
Need to know who was sent what.

**Comment by knmnyn** [comment]
i.e., I sent an email via the system to four students, but the cc:ed copy to me, doesn't indicate who i sent the mail to.

**Comment by franklingu** [comment]
that is not cc. it is bcc. I think for bcc there is no listing of user email addresses right?

or we just use "to" instead

**Comment by knmnyn** [comment]
Ok.  But understand the problem.  I send using the mailer, and I get a copy of the email in my mailbox that is only addressed to me.  I have no idea (in the long run) whom I sent it to.

Best if it can appear just mail that I send normally; e.g., from me and to: each recipient.  Good the mailer can support To: CC: and BCC: fields.
