### ISSUE TITLE
peer evaluation more info may yield error for some users

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#452]

**Comment by franklingu** [comment]
@knmnyn, like which user? could help in debuging

**Comment by knmnyn** [comment]
I'm using student Advay Pal and advisor Si Jun Ke for testing.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
what about the stack trace?
