### ISSUE TITLE
Update survey template (editing) produces error

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#454]
When updating the survey template to change the deadline it produces an error.

"    Survey type : a milestone can have one of each type of survey_templates"

Looks like it is trying to create a new survey template rather than update the original.

**Comment by franklingu** [comment]
Uh... that is because we have two of those now in the system? The
restriction is added later. So maybe there are two before.
Which one you are talking about?

**Comment by knmnyn** [comment]
Milestone #1 Peer Evaluation Template.  Because of the Peer Evaluation bug,
we had to extend the deadline.  I will probably do it directly in the db
console.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
it is another bug. I will check and fix
