### ISSUE TITLE
http://nusskylab-dev.comp.nus.edu.sg/teams CSV download doesn't work

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#460]

**Comment by franklingu** [comment]
maybe related to #461 as well. I will take these two. But i won't be very fast in fixing (any undergraduate or PhD will be taking this project over?)

**Comment by knmnyn** [comment]
I hope I can recruit from Orbital this year for a RA to find a student.
Cross our fingers!

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
