### ISSUE TITLE
Team members can't change their Level of Achievement by themselves

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#462]
They should have write access to this variable.

**Comment by franklingu** [comment]
it is a feature. by design. can change it easily, though

**Comment by knmnyn** [comment]
Ok, no worries then.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
