### ISSUE TITLE
Add link into Nav bar and check for matric number validity

### ISSUE THREAD

**Issue by wengkiat** [nusskylab/nusskylab#469]
1) Add a link in the nav bar for logged in users to see projects and staff (these links are already in the logged out zone)

 

2) Update the user fields to add Matric Number and Home Faculty fields.  Implement a validation check for Matric Numbers.  Allow these to be populated in the User Settings, under "edit user settings" in the 'gear' menu after logging in.

**Comment by wengkiat** [comment]
Hi Prof Kan, @knmnyn, I have done the task as requested and did a pull request.

**Comment by knmnyn** [comment]
Add link into nav bar doesn't seem to appear for all roles (e.g., for admins it doesn't show).  Can you fix?

**Comment by wengkiat** [comment]
@knmnyn, Done up additional requirements in pull request #490

**Comment by wengkiat** [comment]
Resolved in pull request #523
