### ISSUE TITLE
More problems during evaluation period when everyone was using it.

### ISSUE THREAD

**Issue by njyjn** [nusskylab/nusskylab#486]
A possible isolated case. By 'breakdown' the user could have faced a HTTP timeout error or system not recording submission.

From feedback:

> Skylab could be improved in the sense that it doesn't break down too often when there are too many users trying to access it(happened towards the end of my milestone 2 submission).

**Comment by knmnyn** [comment]
May not be easily testable.  Need to have engineering team do load testing or simulate loads, or monitor at milestone deadline timings.
