### ISSUE TITLE
Structure and instruction for README

### ISSUE THREAD

**Issue by njyjn** [nusskylab/nusskylab#487]
Some users were confused on what to include in their README files, also citing that the text input was 'confusing' with Markdown. (Though Markdown is standardized, and plaintext is Markdown without Markdown) Suggest to have visuals on structure like peer evaluation and have an option to switch text input between MD and plain text.

From feedback:

> As mentioned above, a structure for README can be implemented, something like the peer evaluation

> …I think one small thing to improve on is the text input for the READMEs etc. **The markdown within Skylab was slightly confusing though** - is it standardised markdown? Maybe you can just make it plaintext? idk.

**Comment by knmnyn** [comment]
Add in greyed text for a default structure template for the README as a quick fix first.
Add a link to a finished sample README in the instruction text.
