### ISSUE TITLE
Investigate forums implemented using Ruby on rails

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#488]
Check on their interface (especially with respect to db tables).
Check whether it's easy to embed UI wise.
Check whether users can be synchronized with the current Devise role users.

List alternatives directly here, in the issue's thread.

**Comment by njyjn** [comment]
Listing a forum engine 'plug-in' below that may be easy to set up compared to having something from scratch, with porting work that shouldn't be too tedious. Will continue to explore (and maybe test implement to understand it better) Details ahead.

![](https://cloud.githubusercontent.com/assets/216339/20338809/1fbb7dc4-abd1-11e6-9bc3-207b94018931.png)

[Thredded](https://thredded.org/) is a RoR forum engine that is easy to setup, added as a mountable engine.

1a. Interface works out of the box upon installation, with possible theming and customization.

1b. Compatible with PostgreSQL, but to check compatibility of db tables.

- [ ] Check whether our db tables need any form of modification

> Thredded works with SQLite, MySQL (v5.6.4+), and PostgreSQL. Thredded has no infrastructure dependencies other than the database and, if configured in the parent application, the ActiveJob backend dependency such as Redis.

2. As a mountable engine a custom route to the forum can be created (i.e. /forum) and linked through the nav bar.

Demo here: https://thredded.org/thredded/

**Comment by knmnyn** [comment]
Hi @njyjn , looks quite the sweet spot.

@ylhlh @le-minhphuc @wengkiat can you also have a look and as a team, come to a consensus within a week whether this is worth a try?

Suggest you RT(fine)M and then try deploying it in a simple app and see whether you can sub your apps' user tables for thredded's one.

**Comment by njyjn** [comment]
Any comments? I'll start test implementation next week, if none.

**Comment by ylhlh** [comment]
Looks good, I will try implementing it too

**Comment by wengkiat** [comment]
Looks the best out of those I found

**Comment by knmnyn** [comment]
Hi all:

You are welcomed to go ahead with this implementation.  Let’s try to have a meeting arranged sometime next week during Week 1 so that we can all meet one time face to face.  Which days of the week and times are good for you?  I cannot meet on Friday from 10-12 due to my CS3244 class.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore :: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) :: kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by le-minhphuc** [comment]
Most of the materials I read point to this too, Thredded also seems to be quite well-maintained. I'll try implementing it too. Regarding the meeting, I can't meet on Tuesday and Thursday, the rest are okay

**Comment by wengkiat** [comment]
Hi Prof Kan, @knmnyn , I will only be able to make it at night, sorry for the inconvenience!

I believe it would be best for you all to proceed with it and I will get updates from justin, @njyjn

**Comment by ylhlh** [comment]
@knmnyn Friday 12-1 or 4-6 is good for me.

**Comment by njyjn** [comment]
Hi, sflr I just got back. Friday afternoon is good for me too.

**Comment by wengkiat** [comment]
Hi all, if it is possible for the meeting to be on friday 12-1, i can make it.

**Comment by le-minhphuc** [comment]
Friday 1-2 pm will be a good timing for me too

**Comment by knmnyn** [comment]
Hi all:

Great.  Let's meet then at 1-2pm this Friday.  See you at DR12 (at the
Undergraduate office;COM 1 #02-20); near the COM1 Level 2 big open space.

@Rachel, please help me book 1-2pm this Friday for DR12.  I see it is open.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by njyjn** [comment]
👍

**Comment by ylhlh** [comment]
@knmnyn Apologies but I have class from 1-4pm. As mentioned previously, I can only meet 12-1 or 4-6 on Friday

**Comment by wengkiat** [comment]
@knmnyn would 12-1pm be possible?

**Comment by knmnyn** [comment]
Hi all:


12-1pm is actually better for me but I have class until 12pm, so I may be a bit late.  Is that better for all of you instead?

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore :: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) :: kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by wengkiat** [comment]
Sounds Great!

**Comment by le-minhphuc** [comment]
Friday 12pm - 1pm is alright for me too!

**Comment by knmnyn** [comment]
Ok, 12-1pm at DR12 then everyone.  Thanks!  @njyjn is that workable/ok with you?

**Comment by njyjn** [comment]
That works, thanks and see you all!

**Comment by njyjn** [comment]
The forum has been implemented successfully. 

<img width="1680" alt="screen shot 2017-01-13 at 12 34 19" src="https://cloud.githubusercontent.com/assets/10694375/21918501/d8913d5a-d98c-11e6-886c-1e18965049bd.png">

- [ ] To research karma system.

**Comment by njyjn** [comment]
<img width="1680" alt="screen shot 2017-01-28 at 01 09 53" src="https://cloud.githubusercontent.com/assets/10694375/22379970/917e92c6-e4f6-11e6-912d-84c93646b2c1.png">

Simple karma system implemented. User details page now shows 5 most recent posts in the forum. Thoughts?

- [ ] To integrate Forum into navigation bar.

**Comment by knmnyn** [comment]
Looks good so far.  Waiting for cross linking in the user profile pages.
When the basic PR is ready, let's go ahead and field it and see what else needs to be fixed or improved.

**Comment by knmnyn** [comment]
Hi Justin, all:

That is a good place to put information, but it is currently somewhat
duplicated by the /users/369/edit page (edit view) that is available
through the gear menu icon.

Perhaps a good thing to do is to put the show (current) user page as
clearly a part of the user's profile, and have the edit view just make the
fields editable.

The show user page should show all of what is on the edit page, and
integrate the thredded work and show current and available roles for the
user (e.g., if you were a student in 2016, and an advisor for 2017).

There's more but that's ok for now.  Perhaps good to devolve this to a
separate issue after closing the basic PR?


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by njyjn** [comment]
Hi Prof,

This is the view I get:

<img width="1680" alt="screen shot 2017-02-01 at 12 35 49" src="https://cloud.githubusercontent.com/assets/10694375/22495400/01a38cdc-e87b-11e6-91a9-2abe413264e2.png">

Could you send a screenshot so we can see how it looks from your machine and rectify the issue?

In either case we will devise a way to show more details in the users page. 👍

**Comment by knmnyn** [comment]
Hi Justin, all:

Yes, that's how it looks on my machine too. What I was saying is that this
is the /edit page and not the /show page.  The controllers should differ
and the views for the two actions should differ.  However, probably it's
also okay take implemented as a mixed show and edit view, where fields
become editable if they are able to be edited with to uses role, on a
double-click.

Not sure how easy or difficult that is to do in the Rails MVC framework.
I've seen other sites to it so I imagine it's achievable,  but not a
must-have functionality.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
