### ISSUE TITLE
validate method for nus id, user name, team name and project level should be improved

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#49]
nus id: right now it only matches ^[auAU][0-9]{7,7}[A-Za-z]?$
user, team name and project title ^[_A-Za-z0-9]{5,}$

**Comment by franklingu** [comment]
@knmnyn , any suggestions for this? :)

**Comment by franklingu** [comment]
linked to #42

**Comment by Leventhan** [comment]
http://regexpal.com/

**Comment by knmnyn** [comment]
Don't worry so much about this, that is currently ok.  This is a
placeholder.
You eventually want to have OpenID take over for NUS logins.



Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
now this will be closed since we removed front end validation already
