### ISSUE TITLE
Able to view other teams’ milestones (not just the ones to be evaluated)

### ISSUE THREAD

**Issue by njyjn** [nusskylab/nusskylab#491]
User suggesting an open system.

From feedback:

> Perhaps the ability to see other team projects instead of only those we are evaluating.

> Maybe there could be a way to check out everyone's projects too?

**Comment by knmnyn** [comment]
Duplicate of #492 perhaps?

Perhaps because during evaluation see other's milestones after the previous deadline.

**Comment by knmnyn** [comment]
Restrict to current cohort of students AND logged in only?
