### ISSUE TITLE
Able to see a gallery of past projects

### ISSUE THREAD

**Issue by njyjn** [nusskylab/nusskylab#492]
From feedback:

> It would be nice to view other projects (maybe completed ones) and their documentation. It could be under a tab 'Past Projects'. That'll be a form of showcase and the next batch can use it for inspiration. 

> Perhaps an image gallery for all previous Orbital Projects? Not sure how this will impact innovation though.

> Yes, perhaps a gallery tab will spice up the website.

**Comment by knmnyn** [comment]
Related to #473

**Comment by knmnyn** [comment]
u

**Comment by knmnyn** [comment]
Related to earlier deleted branch #489
