### ISSUE TITLE
New window/split window for the evaluation page

### ISSUE THREAD

**Issue by njyjn** [nusskylab/nusskylab#494]
From feedback:

> One suggestion is that since when teams evaluate other teams, we needed to keep switching between tabs (or windows) to read the write-ups and write the evaluation, maybe the write-ups can hover around during evaluation?

> One suggestion though... Perhaps for the evaluation pages, a split screen could be implemented? I found it rather tedious to be toggling between peer groups submissions and the evaluation form. Maybe they can be both implemented on the same screen, so that the evaluating party may make quick references to the READMEs and Project logs, in case they are unable to remember the stated implementations mentioned by their peers. "

> Should open another window instead of changing the web page when openning the milestone page in the evaluation page for comparative purposes.

**Comment by knmnyn** [comment]
Perhaps add a secondary link to "open in separate tab/window"

**Comment by knmnyn** [comment]
Add fixture instructions on how to accomplish this easiest.
