### ISSUE TITLE
Crosslink stuff together like Milestones

### ISSUE THREAD

**Issue by linhany** [nusskylab/nusskylab#499]

**Comment by knmnyn** [comment]
Find other such issues and add them as separate issues.

There are ones per role.

**Comment by ylhlh** [comment]
Does anyone still remember what this is referring to? Is it grouping the survey templates under milestones or something. I'm also not sure what are the issues per role, please let me know if you do so I can work on this

**Comment by knmnyn** [comment]
@ylhlh it is about the functionality presented in any one controller view.  There are many opportunities for a controller show action to present more information than is strictly necessary.  Perhaps it's better to enumerate some places where cross-linking could be of use instead (as stated in the earlier comment).

For example, the user/student views can show the relevant information about the associated team and the student/user.  

Team views don't show the milestones submitted or the peer reviews on them.
