### ISSUE TITLE
Wiki page for skylab for integrating Thredded

### ISSUE THREAD

**Issue by ylhlh** [nusskylab/nusskylab#500]
Documentation E.g. thredded integration

**Comment by knmnyn** [comment]
We may need another member to help proofcheck the documentation.  @wengkiat

**Comment by njyjn** [comment]
Done! https://github.com/nusskylab/nusskylab/wiki/Thredded-Setup-Guide

@wengkiat to proofcheck and close.

**Comment by wengkiat** [comment]
Approved and good to go!

Closed.
