### ISSUE TITLE
Make fixture users

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#502]
Create dummy users from example.com for each role

**Comment by ylhlh** [comment]
Created:
student student@example.com
facilitator facilitator@example.com
adviser adviser@example.com
tutor tutor@example.com
mentor mentor@example.com
To preview as role, go to Users, ctr-f the name, and click preview as.

**Comment by zhaojin42** [comment]
Somehow there are already a few students who have registered on Skylab. I don't think we need to remove them or remove the registration button. Just be careful not to remove them if you are planning to remove the fixture data later.
