### ISSUE TITLE
assign roles per user per cohort on web interface

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#503]
Right now we have to do this by postgres SQL insert statement :(

**Comment by knmnyn** [comment]
Actually able to do this via individual user role screens via Create new X.  But only defaults to current cohort.

**Comment by knmnyn** [comment]
Actually can.

**Comment by njyjn** [comment]
Will continue to add role assignment button next to names.

**Comment by zhaojin42** [comment]
It's not possible to insert a role to a specific cohort via the interface now.

We will need this at least for the admin role. Otherwise it will just expire every year.
