### ISSUE TITLE
Tests failing because of matric number constraints. 

### ISSUE THREAD

**Issue by njyjn** [nusskylab/nusskylab#504]
Travis CI log here: https://travis-ci.org/nusskylab/nusskylab/builds/191837949

Most tests return error **Validation failed: Matric number can't be blank, Matric number : Invalid matric number**

> 1) AdminsController GET #index user logged in but not admin should redirect to home_path for non_admin
     Failure/Error: Unable to find matching line from backtrace
     ActiveRecord::RecordInvalid:
       Validation failed: Matric number can't be blank, Matric number : Invalid matric number
     # ./spec/support/controller_macros.rb:17:in `block in login_user'

Solution: To fix text cases/interface.

**Comment by wengkiat** [comment]
It is already resolved in my pull request which has not been merged.
 
The regax has been modified to allow for blank inputs for matric numbers

**Comment by njyjn** [comment]
Reference #495. To review.

**Comment by knmnyn** [comment]
Thanks for this.  Please assign part of the Skylab Eng team to review.

**Comment by knmnyn** [comment]
Ok, going to approve the earlier PR, but please note the earlier problem...

> The matric has the last character as a check letter. Please ensure that your algorithm validates this when entered by a student.
> 
> http://interrobeng.com/2014/01/19/nus-matriculation-number-check-digit-algorithm/

**Comment by wengkiat** [comment]
@knmnyn , yeap, will fix that

**Comment by wengkiat** [comment]
Resolved in pull request #523
