### ISSUE TITLE
No way to update profile picture?

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#518]
I could not find a way to update my profile picture in "Edit User Settings". Is there a way to do so in the system?

**Comment by knmnyn** [comment]
Hi Jin:

The profile pictures are sourced from gravatar.org.  Our instructions need
to make that more clear though...


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by zhaojin42** [comment]
OK. I will try to set up my gravatar.org then.

**Comment by njyjn** [comment]
Instructions to change have been added in #519.
