### ISSUE TITLE
form name validation method adjustment; html refactoring(position of role='form' is wrong, use locals over instance variable)

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#52]
this is linked to #49 
however, for batch creation of students, disallowing spaces would just be stupid for user name. that is why currently user model validation does include spaces

**Comment by Leventhan** [comment]
For Rails, the best practice is to instead use [simple_form](https://github.com/plataformatec/simple_form) to handle model form generation and validation.

**Comment by franklingu** [comment]
well, thanks for the advice. will be considering this for later development

**Comment by franklingu** [comment]
this is a scattered around. but submission and peer_evaluation should be okay

**Comment by franklingu** [comment]
this will be cleared when going through each actions. a bit too general too
