### ISSUE TITLE
Thredded: mail notification doesn't seem to work.

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#521]

**Comment by njyjn** [comment]
Can I check that you are able to post a reply successfully, but unable to get email notifications?

**Comment by njyjn** [comment]
I get this error on my local system: https://www.ruby-forum.com/topic/153066

Apparently, we need to restart the rails server everytime a change to `config/thredded.rb` is made. Let's do that and see if replying on the forum works.

**Comment by knmnyn** [comment]
I cannot post a reply

**Comment by knmnyn** [comment]
Moved discussion to #524 and to Slack #skylab-engineering
