### ISSUE TITLE
DB migration issue (relating to #524)

### ISSUE THREAD

**Issue by njyjn** [nusskylab/nusskylab#526]
_Due to #524, a migration issue due to adding index to unique entries in the users db, based on names, arose. But there are some duplicate records with same names. This fix was suggested on Slack:_

> There may be duplicate names. Ok. The reason why the error is produced is because I did a migration to add indexes to each field, given they are unique. But our users table already has indexes, so it is redundant. Could we rollback `20170307170913_add_index_to_username_in_users_for_thredded`?
> `rake db:migrate:down VERSION=20170307170913` (edited)

**Comment by knmnyn** [comment]
Done.
