### ISSUE TITLE
Sort order and date of registration for the students page?

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#527]
I can't seem to figure out the sort order of the students page. It does not seem to be based on the name or date of registration. 

Is it possible to show the date of registration (e.g., the date on which the registration form was completed) on the page? Otherwise, it is quite difficult to figure out which are the new students and which students should be accepted.

**Comment by njyjn** [comment]
Hi Jin, can I clarify, the date the user registered as a user, or as a student? Because I don’t think users are registered as students immediately?

**Comment by zhaojin42** [comment]
I am interested in finding out when a particular "user" completes the registration form and becomes a "student" in the system.

Thanks!

**Comment by zhaojin42** [comment]
Thanks for updating the system!

Just one more thing, is it possible to include registration date/time in the CSV file generated from the students page?

**Comment by njyjn** [comment]
Sure @zhaojin42, are you comfortable with format 2017-01-13 10:06:27 +0800?

**Comment by zhaojin42** [comment]
I think "date,time" (without the timezone) would be great (something like 2017-01-13,10:06:27).

Thanks a lot!
