### ISSUE TITLE
Sending out invitation to someone who has not registered in the system

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#529]
Can a student who has registered in the system invite another student who has not registered in the system to form a team? 

Some of the students thought they could do so but they ended up getting the "Email address not recognized" error.

Anyway, this seems to be a useful feature to be incorporated into the future version of the system (if it is not already in).

**Comment by knmnyn** [comment]
No, currently this functionality is not implemented.  The students should work together to register in the system and pair up, as per the video.

Email from the system is still not working correctly in some cases, especially with respect to the forum.

**Comment by zhaojin42** [comment]
I see. Thanks for the clarification!

**Comment by zhaojin42** [comment]
Nowadays the vacancies run out within two days so I don't think there is a need to allow this.
