### ISSUE TITLE
display errors to users if model validation returns error msg: submission#new and #edit

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#53]

**Comment by Leventhan** [comment]
Are you using bootstrap? I have a `flash_messages` partial you can easily re-use here.

**Comment by knmnyn** [comment]
Think so.  Not sure what other CSS JS combo @franklingu is using above that.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by franklingu** [comment]
right now this is simply not explored yet. msgs are hidden--meaning that users will not see but msgs are their

**Comment by franklingu** [comment]
will be linked with #49 , #51 and 3 of them will be solve together

**Comment by franklingu** [comment]
https://github.com/DavyJonesLocker/client_side_validations

http://stackoverflow.com/questions/18180392/ruby-on-rails-client-side-validation-simple-form-javascript-error

right now I will remove all front end validations for all forms that I am currently working with. with come back to this issue later
