### ISSUE TITLE
No option to invite team member

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#537]
I have received a few messages from students that they are unable to find the option to invite team member. 

This seems to start happening after we changed the pending flags of the students from true to false. 

One example is the following student: 
http://nusskylab-dev.comp.nus.edu.sg/users/1254

Could anyone help to check?

**Comment by njyjn** [comment]
What do the pending flags represent?

**Comment by zhaojin42** [comment]
After the students have registered, their "pending"  flags are set to "true" indicating that their registrations are "pending approval". At this stage, the students are allowed to update the registration form and invite a teammate via the "User roles" tab. (e.g. http://nusskylab-dev.comp.nus.edu.sg/users/1269)
![pending-no-teammate](https://cloud.githubusercontent.com/assets/9313999/24847927/ca56260c-1df6-11e7-9343-7e6f78096b32.png)

However, last week we have confirmed the registration of a large batch students by changing the "pending“ flag from true to false, indicating that their registrations have been "approved". Subsequently. the "User roles" tab no longer shows the button to update the registration for or invite a teammate. (e.g., http://nusskylab-dev.comp.nus.edu.sg/users/1068)
![accepted-no-teammate](https://cloud.githubusercontent.com/assets/9313999/24847932/d024ffc2-1df6-11e7-8808-692f85944c06.png)

**Comment by njyjn** [comment]
> By the way, is it possible for the students to change teams after they have formed one?

@zhaojin42 This is only possible through the admin page, under `Users/Edit`.
