### ISSUE TITLE
Problem with account creation when signing in with NUS Open ID

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#538]
A student is able to log into NUS Open ID but is unable to create an account in Skylab.

![screenshot](https://cloud.githubusercontent.com/assets/9313999/24769818/6a23d8f6-1b3a-11e7-899b-f1a57564495b.JPG)
![screenshot1](https://cloud.githubusercontent.com/assets/9313999/24769821/6a2ddb30-1b3a-11e7-8292-56b5a24b8f81.JPG)
![screenshot2](https://cloud.githubusercontent.com/assets/9313999/24769820/6a2b68f0-1b3a-11e7-8e3b-cb968c62cf60.JPG)
![screenshot3](https://cloud.githubusercontent.com/assets/9313999/24769819/6a26d5ba-1b3a-11e7-986a-bf7b4e7ba4cf.JPG)

**Comment by njyjn** [comment]
@zhaojin42 Please get the user to try again. The link their browser should show is `https://openid.nus.edu.sg/auth/index/?openid.ax_if_available=ext4%2Cext5%2Cext6%2Cext7%2Cext8&openid.ax_mode=fetch_request&openid.ax_required=ext0%2Cext1%2Cext2%2Cext3&openid.ax_type_ext0=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ax_type_ext1=http%3A%2F%2Faxschema.org%2FnamePerson&openid.ax_type_ext2=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ax_type_ext3=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ax_type_ext4=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffriendly&openid.ax_type_ext5=http%3A%2F%2Faxschema.org%2Fcontact%2Fcity%2Fhome&openid.ax_type_ext6=http%3A%2F%2Faxschema.org%2Fcontact%2Fstate%2Fhome&openid.ax_type_ext7=http%3A%2F%2Faxschema.org%2Fcontact%2Fweb%2Fdefault&openid.ax_type_ext8=http%3A%2F%2Faxschema.org%2Fmedia%2Fimage%2Faspect11&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.ax=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.realm=http%3A%2F%2Fnusskylab-dev.comp.nus.edu.sg&openid.return_to=http%3A%2F%2Fnusskylab-dev.comp.nus.edu.sg%2Fauth%2FNUS%2Fcallback%3F_method%3Dpost&openid.sreg.optional=postcode%2Cnickname&openid.sreg.required=email%2Cfullname&controller=server&action=index&module=default` 

and not `openid.nus.edu.sg/auth`

Thanks!

**Comment by zhaojin42** [comment]
Thanks! I will do that.

But just to clarify, the student did use the button "sign-in with NUS" in Skylab and encountered the error of "Invalid credentials...". Subsequently, I asked her to double check whether her NUS Open ID was working and hence the screenshots.

**Comment by zhaojin42** [comment]
Here is the reply from the student:

![unnamed 3](https://cloud.githubusercontent.com/assets/9313999/24877447/f55b3c64-1e61-11e7-9614-a2739f28ed4c.jpg)

**Comment by zhaojin42** [comment]
It is possible to create a user manually without using NUS Open ID?

The information of the student is as follows: 
Name: Li Liwei
Email address: e0032128@u.nus.edu

**Comment by knmnyn** [comment]
Hi Jin:

Yes, use the users tab and hit the create user button.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by zhaojin42** [comment]
Hi Min,

Thanks! 

So I should put "provider_nil" for the "provider" field? What password will the student need to use to sign in?

Regards,
Jin

**Comment by knmnyn** [comment]
Hi Jin:

I'm not sure.  I think the code will set a random password that can be
mailed to the student using the "forget password" method if you set the
appropriate email address.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
