### ISSUE TITLE
Instructions missing for Read me and Project log in all milestones

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#540]
![image](https://cloud.githubusercontent.com/assets/9313999/25693081/a84c566c-30d9-11e7-825c-4c9db6226a85.png)

According to the past year video, there should be some instructions for Read me and Project log in all milestones. But they are now missing from all milestones. 

Please recover those instructions and put them back in. In addition, it would be great if it is possible for me to edit those instructions via Skylab.

**Comment by njyjn** [comment]
Hi @zhaojin42 , how did you access the above page? I want to replicate it on my system.

**Comment by zhaojin42** [comment]
I have added Demos student 1/2/X/Y into the current cohort. If you "preview as" one of those accounts via the "Users" page, you can try to create milestones and see that page. For example, if you "preview as" "Demo Student 1", then the page for creating milestones is at http://nusskylab-dev.comp.nus.edu.sg/milestones/7/teams/1419/submissions/new. Just click create to see reach the screen shown above.

**Comment by njyjn** [comment]
Thanks @zhaojin42 . May I have a look at the past year video? The code does not seem to have any opening for instructions.

```
app/views/submissions/_submission_form.html.erb

<%= simple_form_for locals[:submission], wrapper: :vertical_form,
                    url: {action: (locals[:is_new] ? 'create' : 'update')} do |f| %>
    <%= f.error_notification %>
    <br><br>
    <div class="form-group submission_milestone_name">
      <label class="control-label col-sm-2" for="submission_milestone_name" style="padding-left: 0;">Milestone Name: </label>
      <div class="col-sm-10">
        <p><strong class="form-control-static" id="submission_milestone_name"><%= locals[:milestone].name %></strong></p>
      </div>
    </div>
    <%= f.input :read_me, input_html: {class: 'tinymce'}, placeholder: 'Input project readme', rows: '3', required: true %>
    <br>
    <%= f.input :project_log, input_html: {class: 'tinymce'}, placeholder: 'Input project log', rows: '3', required: true %>
    <%= f.input :video_link, placeholder: 'Input project video link', required: true %>
    <%= f.input :poster_link, placeholder: 'Input project poster link', required: true %>
    <p><strong>Allow public viewers to see your video?</strong></p>
    <%= radio_button("submission", "show_public" ,true) %>
    <%= label_tag(:show_public_yes, "Yes") %>
    <%= radio_button("submission", "show_public" ,false) %>
    <%= label_tag(:show_public_no, "No") %>
    <%= f.button :submit_centred, class: 'btn-success' %>
<% end %>
```

**Comment by zhaojin42** [comment]
Thanks @njyjn . I checked the past year video https://youtu.be/ZRMaxD-sCw0?t=3m10s and realized that Min showed an existing milestone report. So I am not 100% sure that there were instructions in the form. Anyway, if I prepare a rough guideline, could you find some way to display it in (or together with) the form?

**Comment by njyjn** [comment]
Hi @zhaojin42 , sure i will look into it

**Comment by njyjn** [comment]
How would you like to display the guideline?

**Comment by knmnyn** [comment]
Hi @njyjn I am at Liftoff now and I did hardcoded changes to the form view to fix this for now.  Please refactor if needed and if so, please re-open the issue.  Thanks!
