### ISSUE TITLE
Allowing advisors to see all teams when creating evaluation relations.

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#546]
The advisors are allowed to create peer evaluation relations but only among his/her own teams. http://nusskylab-dev.comp.nus.edu.sg/evaluatings

For this round, the evaluation groups are small so it is better if the relations can be created across evaluation groups otherwise some of the teams (esp the Apollo teams) might not get evaluated by teams of similar levels. In additions, It is also better for teams to get to know teams outside their own evaluation groups for exposure purposes.

Is possible to do a quick patch so that the advisors could see all teams when they are creating evaluation relations?

This is kind of urgent since the deadline for Milestone 1 is next Monday.

**Comment by njyjn** [comment]
Ok @zhaojin42 , looking into it at the soonest. In the meanwhile, I would like to request to bring Hong Shaoyang on board to assist me. He is a current Orbital advisor with CS background who expressed interest in helping out with the system. Let me know if this is possible, I believe it will expedite things. Thanks!

**Comment by njyjn** [comment]
Clarification: Advisors will be able to see all teams, in the **evaluated** or **evaluator** field?

<img width="1165" alt="screen shot 2017-05-26 at 09 32 09" src="https://cloud.githubusercontent.com/assets/10694375/26477155/378b871c-41f6-11e7-9033-7fa6a1441bb4.png">

Currently I believe the Admin (me) can see all teams, is this desired for the Advisor too?

**Comment by zhaojin42** [comment]
Please make the advisors to see all teams in both fields. I know this might cause some undesired problems but let's see how it goes for this Milestone and we can adjust later if needed.

**Comment by zhaojin42** [comment]
I am ok with adding shaoyang as a developer. Could you follow up with @knmnyn on this?

**Comment by njyjn** [comment]
@zhaojin42 I am making some progress, can I check that you only want to allow advisors to **create** relations and nothing else?

**Comment by zhaojin42** [comment]
I think the current design already allows the advisors to delete and update. It is just that they can only see their own teams. To keep things simple, is it better to just reuse the admin view for the advisors for that page?
