### ISSUE TITLE
Line breaks removed when the feedback from Milestone evaluation is displayed

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#548]
An advisor just sent me an email about the display of feedback for Milestone evaluation. It is not a major issue but it would be good to have it fixed before the next Milestone.

-----
This is probably a minor issue, but just to let you know that I noticed the advisor evaluation form on skylab tends to remove linebreaks (i.e. for paragraphing purpose). Since some of the feedback might be a bit long, I'm concerned that without linebreaks it gets hard to read and rather overwhelming for the students.

How it looks when editing (http://nusskylab-dev.comp.nus.edu.sg/milestones/7/advisers/54/peer_evaluations/3337/edit)

![unnamed-9](https://cloud.githubusercontent.com/assets/9313999/26670318/ca662410-46e3-11e7-8c98-3b288a6416a8.png)

How it looks when viewed. (http://nusskylab-dev.comp.nus.edu.sg/milestones/7/advisers/54/peer_evaluations/3337)
![unnamed](https://cloud.githubusercontent.com/assets/9313999/26670323/cddad1ea-46e3-11e7-9a80-7c227063bb3d.png)

**Comment by knmnyn** [comment]
Looks like @njyjn fixed this.  I see the desired fix in the site.

![image](https://user-images.githubusercontent.com/217067/26893035-bd3227d6-4bec-11e7-9cf0-c9dea615e1a6.png)

Closing #549.
