### ISSUE TITLE
Feature to freeze / unfreeze team information for all teams.

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#557]
As of now, it is possible for a team to silently change its level of achievement (along other information) after Milestone 3 and it is hard to trace such changes. 

For example, a team may indicate in the milestone 3 submission that its LoA is PG in order to pass the evaluation, but change the LoA to Apollo 11 after the evaluation deadline. Then the team will have Apollo 11 on the certificate without actually being evaluating at that level.

Therefore, there needs to be a function to freeze / unfreeze such information. The teams must go through the advisor / coordinator to make changes once the information is frozen.

**Comment by knmnyn** [comment]
Related to #556
