### ISSUE TITLE
Fix documentation for deployment

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#559]
Continue to update the wiki with installation instructions for the nusskylab.

Don't close this issue -- just comment below if you make changes.

**Comment by charlesgoh** [comment]
Added a bullet point for the problems encountered during the installation of capybara-webkit and qt

**Comment by bokwoon95** [comment]
Added a set of local setup instructions for macOS Mojave #654

**Comment by e0003133** [comment]
Updated setup for vagrant (issues #568 & #573 )
