### ISSUE TITLE
use file upload for students csv

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#56]
the file is simply too long for copy and paste

**Comment by Leventhan** [comment]
You can use the `paperclip` gem or [carrierwave](https://github.com/carrierwaveuploader/carrierwave) and AWS S3 to store files like this. On S3, you can also make it private if it's your requirement.

**Comment by franklingu** [comment]
well, rails can handle file upload by itself. and we do not need to store it anywhere. after admin uploads, we process the file and then the file is not of use any more

**Comment by franklingu** [comment]
wait on #62

**Comment by franklingu** [comment]
extension of #12
