### ISSUE TITLE
Update gems

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#561]
Update the gems that Skylab is dependent on to remove system vulnerabilities in the dependent libraries.  Contact Min if you cannot see these problems in the Gemlock file.

**Comment by charlesgoh** [comment]
@knmnyn is there a set procedure for updating the gems (i.e. do we need to do any regression testing)?

**Comment by knmnyn** [comment]
No, there isn't.  Do try to check whether your installation is stable after
updating any gems.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by lincredibleJC** [comment]
@knmnyn @charlesgoh I'm currently updating the gems to remove system vulnerabilities.
Is there a way to check whether it the build is stable after updating the gems. I'm currently just running `bundle check` to verify if dependencies are satisfied by installed gems and running
```
bundle exec rake db:test:prepare
bundle exec rspec spec
```
no tests failed as of yet.

**Comment by lincredibleJC** [comment]
@knmnyn @charlesgoh My branch is currently getting a Travis build failed because of a devise secret key. Should this be the case? or am I supposed to add the secret key in?

**Comment by knmnyn** [comment]
Hi Jiachao:

Secret keys are not supposed to be committed and Travis CI should be able
to generate its own key when needed.  I think there's probably
misconfiguration on our side within the repo.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
