### ISSUE TITLE
Virtual box is unable to open a session on vagrant up

### ISSUE THREAD

**Issue by lincredibleJC** [nusskylab/nusskylab#562]
I'm facing some difficulty setting up the repo with vagrant. 

I cloned the repo to my desktop, opened up cmd prompt in admin mode and ran vagrant up.
Here is the log that i have:

![image](https://user-images.githubusercontent.com/22949932/34456299-0dec3a58-edce-11e7-92d7-731bfd3ae575.png)

Going by the error codes, apparently, it's a problem with VirtualBox being unable to start VMs on some windows hosts. I've also tried some of the fixes recommended online but none of them are working for me.

Did anybody else face the same error?
Are there also specific versions of VirtualBox that we should use instead of the latest one?

**Comment by knmnyn** [comment]
@njyjn @wengkiat either of you can resolve issues in this thread?

**Comment by wengkiat** [comment]
This issue is indeed related to the windows OS where virtual box may not be able to run on certain Windows OS.
I suggest setting it up manually, 
https://github.com/nusskylab/nusskylab/wiki/Local-Installations-(Non-Vagrant)

**Comment by Skaty** [comment]
@lincredibleJC might be due to the fact that Intel VT-x or AMD-V is disabled in BIOS (or in rare cases, especially old processors, it might not even be a feature). As the guest runs in 64-bit mode, your OS won't even start up properly in VirtualBox, which results in the timeout.

**Comment by lincredibleJC** [comment]
@Skaty I've checked the BIOS and it's confirmed that Virtualisation has been turned on. I'm still looking into another way to set up

**Comment by Skaty** [comment]
@lincredibleJC Since the virtualbox image has been created, try navigating to `%userprofile%\VirtualBox VMs\nusskylab` and run the VM (double-click on the VM file). See if your VM boots up to the default shell.

**Comment by lincredibleJC** [comment]
@Skaty I'm currently getting this

![image](https://user-images.githubusercontent.com/22949932/35722350-e3da4390-0830-11e8-9c2b-1cd1dd032255.png)

**Comment by lincredibleJC** [comment]
Apparently virtualbox and vagrant do not play well together on windows 10, and my best solution was to get a MacBook. It works much better on Mac as ruby is already built in.

**Comment by yhchong** [comment]
For Windows,  VT-x needs to be enabled and Hyper-V needs to be disabled.

[How to enable GUI to see the error]
https://stackoverflow.com/questions/23293071/timed-out-while-waiting-for-the-machine-to-boot-when-vagrant-up

[How to disable Hyper-V]
https://stackoverflow.com/questions/50053255/virtualbox-raw-mode-is-unavailable-courtesy-of-hyper-v-windows-10

**Comment by lincredibleJC** [comment]
Yea I tried doing that too and it didn't work.
