### ISSUE TITLE
psql vagrant user

### ISSUE THREAD

**Issue by knmnyn** [nusskylab/nusskylab#563]
Via email:

> I am one of the student trying to help out with the Skylab system. I managed to log in using NUS Open ID and they requested me to trust 0.0.0.0:3000. Eventually, I received an error message as attached above. I thought maybe I should add my user inside first so I run "psql -d nusskylab_dev" on vagrant and they requested a password to authenticate the user "vagrant". I tried to debug and looked through the issues but I am not sure how do i go about solving this. Hopefully you can give me some advice on this?

**Comment by wengkiat** [comment]
The psql may not have been set up properly during the vagrant run, what the student could do is in the vagrant instance, follow the local set up just to set up psql.

**Comment by anhhuynh2111** [comment]
After`initdb path/to/new-folder-name-for-db`, I ran `postgres -D path/to/new-folder-name-for-db` and got following error:

```
[vagrant@nusskylab vagrant]$ postgres -D postgres
LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
```

So I tried `ps aux | grep postgres`:

```
postgres  9064  0.0  0.9 234936  9348 ?        S    09:22   0:00 /usr/bin/postgres -D /var/lib/pgsql/data -p 5432
postgres  9065  0.0  0.1 194684  1516 ?        Ss   09:22   0:00 postgres: logger process   
postgres  9067  0.0  0.1 234936  1716 ?        Ss   09:22   0:00 postgres: checkpointer process   
postgres  9068  0.0  0.1 234936  1988 ?        Ss   09:22   0:00 postgres: writer process   
postgres  9069  0.0  0.1 234936  1720 ?        Ss   09:22   0:00 postgres: wal writer process   
postgres  9070  0.0  0.2 235792  2944 ?        Ss   09:22   0:00 postgres: autovacuum launcher process   
postgres  9071  0.0  0.1 194812  1772 ?        Ss   09:22   0:00 postgres: stats collector process   
postgres  9656  0.0  0.8 237560  8732 ?        Ss   09:35   0:00 postgres: nusskylab 
vagrant  10190  0.0  0.0 112632   728 pts/1    R+   09:53   0:00 grep --color=auto postgre
```

Then ran `sudo pkill -u postgres` to kill postgres process and ran `postgres -D path/to/new-folder-name-for-db` again. I got this error:
`FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": Permission denied`. Please advise me how I should proceed further. Thanks.

**Comment by jacoblipech** [comment]
Hi. I have the same problem as above. I tried reinstalling everything and they still require a password before I can access the nusskylab_dev using psql. Please advice how should I proceed too. Thank You.

**Comment by njyjn** [comment]
When you force kill a postgres process usually there is a lock file that prevents one from doing additional stuff to the db. Try looking for that lock file and deleting it.

**Comment by jacoblipech** [comment]
the password is in the development guide. closing this issue.
