### ISSUE TITLE
Installing Capybara Webkit on Mac

### ISSUE THREAD

**Issue by charlesgoh** [nusskylab/nusskylab#564]
https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-sierra-1012-el-capitan-1011-and-yosemite-1010

Can someone advise on how to this:
` echo 'export PATH="$(brew --prefix qt@5.5)/bin:$PATH"' >> ~/.bashrc`

I added this to .bash_profile but capybara still failed to install. Where should I be putting this?

**Comment by charlesgoh** [comment]
https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-sierra-1012-el-capitan-1011-and-yosemite-1010

Can someone advise on how to this:
` echo 'export PATH="$(brew --prefix qt@5.5)/bin:$PATH"' >> ~/.bashrc`

I added this to .base_profile but capybara still failed to install. Where should I be putting this?

**Comment by lincredibleJC** [comment]
Yes, I'm facing the same problem too. But I'm Running MacOS on a VM instead.

**Comment by charlesgoh** [comment]
@lincredibleJC It shouldn't make a difference. And yes that is the problem I had.
<img width="1218" alt="screen shot 2018-01-07 at 10 40 47 pm" src="https://user-images.githubusercontent.com/15852016/34650408-d56960a0-f3fb-11e7-9e25-5a578c712b3a.png">

**Comment by knmnyn** [comment]
Depending on your shell, .bash_profile may not be sourced when you run your shell.  Check that it is actually being picked up (an alternative location is .profile).

**Comment by charlesgoh** [comment]
Tried the force link solution also but receiving the same error. Any mac devs know a fix to this? 

@knmnyn It seems that the echo command inserted it into .bashrc. However, either the path is not registering or there is something else causing this error.

**Comment by charlesgoh** [comment]
@lincredibleJC 
Two possible issues:
**QT**
Mac users need to use qt5.5 and link it manually (correct me if I'm wrong). See the link below.  When you execute the command to insert the PATH, insert it into .bash_profile (mac) or .bashrc (linux). 
`echo 'export PATH="$(brew --prefix qt@5.5)/bin:$PATH"' >> ~/.bash_profile`
https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-sierra-1012-el-capitan-1011-and-yosemite-1010

**Xcode and CLT**
Install Xcode and Command Line Tools, and agree to all license agreements. If you install CLT after Xcode, you may need to follow the instructions linked below:
https://stackoverflow.com/questions/33728905/qt-creator-project-error-xcode-not-set-up-properly-you-may-need-to-confirm-t#35098040

**Comment by knmnyn** [comment]
Thanks Charles!


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by knmnyn** [comment]
Hi all, you may want to document your challenges in performing this stage in the Wiki or by changing the README and issuing a PR.  Thanks everyone.
