### ISSUE TITLE
initdb: command not found linux system (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by lincredibleJC** [nusskylab/nusskylab#565]
I'm trying the local setup on a linux ubuntu vm and I'm facing this issue with postgres commands. initdb seems to not be available in as a command, even after consulting the documentation.

![image](https://user-images.githubusercontent.com/22949932/34649739-ca821508-f3ef-11e7-9c96-a390065412c5.png)

This is a problem in windows too. Is there something that we are missing out on how to use postgres?

**Comment by knmnyn** [comment]
Hi @njyjn @wengkiat , not sure whether you encountered problems with postgres.  Seems like the new cohort is having problems.  Could it be due to different versions of pg?

**Comment by charlesgoh** [comment]
@lincredibleJC Is it possible that postgres is not installed? 
`sudo apt-get install postgresql`

**Comment by lincredibleJC** [comment]
Nope, I definitely installed it.

**Comment by knmnyn** [comment]
Seems like this is an issue with using a newer version of postgres.  The one on the vagrant virtualbox centos is:
```
 [vagrant@nusskylab config]$ uname -a
Linux nusskylab 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@nusskylab config]$ psql --version
psql (PostgreSQL) 9.2.23
```

**Comment by njyjn** [comment]
The instructions in the wiki were written specifically for MacOS. Adapt from here for CentOS: https://github.com/nusskylab/nusskylab/blob/master/bootstrap.sh

**Comment by lincredibleJC** [comment]
I am actually getting a little further in the installation now.

Currently I'm doing the bundle rake, following the bootstrap.sh commands.

I'm able to install the gems and DB and also install user and initdb after adding it to path:

![add to path](https://user-images.githubusercontent.com/22949932/35721014-2495024a-082b-11e8-805b-e494d8d1947c.png)

But for the bundle rake, I'm getting a Peer authentication failed error

![bundle rake create peer authentication fail](https://user-images.githubusercontent.com/22949932/35720937-cf928196-082a-11e8-8cfb-08fd27dbff1b.png)
