### ISSUE TITLE
Key Conflict when running bundle exec commands

### ISSUE THREAD

**Issue by charlesgoh** [nusskylab/nusskylab#566]
I'm attempting to find a solution to a problem encountered in step 3 of:
https://github.com/nusskylab/nusskylab/wiki/Local-Installations-(Non-Vagrant)
when running the bundle exec commands.

Has anyone encountered these key conflict issues before?
<img width="1346" alt="screen shot 2018-01-10 at 11 13 55 am" src="https://user-images.githubusercontent.com/15852016/34754220-5fd1daea-f5f7-11e7-9cb7-e64d16b627d8.png">

**Comment by knmnyn** [comment]
Hi @charlesgoh Yes, these are even in the production version of skylab.  We hope to fix some of these conflicts before Skylab is put into use this year, but they are not urgent.

**Comment by charlesgoh** [comment]
The guide has been updated to indicate that it is outdated.
