### ISSUE TITLE
Devise.secret_key is not set

### ISSUE THREAD

**Issue by Kowalski985** [nusskylab/nusskylab#568]
Devise.secret_key is not set when `vagrant provision` is run. As a result the rake files can't be executed properly. Setting up using the alternative method without vagrant also results in the same issue.

![image](https://user-images.githubusercontent.com/13115806/35274140-faf4cf18-0075-11e8-9e9c-bef24eba325e.png)

**Comment by njyjn** [comment]
Set it in this file, you can use the secret key given above ^^ https://github.com/nusskylab/nusskylab/blob/master/config/initializers/devise.rb

**Comment by potatowagon** [comment]
Thanks Justin, faced this same problem too.  Just want to add,
After setting secret key in devise.rb, remember to restart application by
`vagrant reload`
then do the usual
`vagrant provision`
`vagrant ssh`
so newly added secret key will be loaded. If not the same error message will keep reappearing.

**Comment by knmnyn** [comment]
This also seems to be a problem on Travis CI, when the latest PR from @Skaty was posted.
