### ISSUE TITLE
Add Ignition (Milestone #0) into the team page

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#569]
For each team, we should store the slide they have submitted and the video of their ignition presentation (if available).

**Comment by knmnyn** [comment]
Student to provide link to slide as an img, displayable link for ignition.
Show preview thumbnail of provided uploaded link.

**Comment by lincredibleJC** [comment]
@knmnyn @zhaojin42 Just to clarify, the orbiters will have to submit a link to the slide they'll be using for the pitch and we'll be storing that link. Then we'll be video record their pitch, upload it to youtube, and add that private link to the teams so that others can view it. Is that right?

**Comment by zhaojin42** [comment]
Yes. That's correct.

**Comment by knmnyn** [comment]
![image](https://user-images.githubusercontent.com/217067/38247652-a2c490be-3778-11e8-87ff-d606b9e6760f.png)
The link should be somewhere here.  On the team page not on the individual students' page.

**Comment by lincredibleJC** [comment]
@zhaojin42 I have just added the two requested fields to the teams' page. Editing of the two links is currently only available to admins.

I'm looking at the surveys and I'm not very sure how they are administered to the students. Also, the Submission already milestone already asks students for their pitch slides. Should we make it such that we can get the link straight from the submission and not have to ask the students for the links again?

**Comment by zhaojin42** [comment]
![image](https://user-images.githubusercontent.com/9313999/38477994-983f81c0-3be8-11e8-960b-e1865f25514c.png)

@knmnyn @lincredibleJC I was thinking of having the links captured just like how they would submit for other milestones.

**Comment by knmnyn** [comment]
Hi Jin, all:

Sounds good.  This way they will be more familiar with submitting
Milestones too.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
