### ISSUE TITLE
Footer not flushed to the bottom of the page

### ISSUE THREAD

**Issue by Skaty** [nusskylab/nusskylab#574]
It seems that the footer is floating a little above the bottom of the page. This is a minor display issue, but the floating footer causes the 'return to top' button to float behind the footer, if the user scrolls all the way down.

## Replicating the Issue
![image](https://user-images.githubusercontent.com/978676/35736041-abbb18e6-0861-11e8-89f0-73962eff1835.png)

## Potential Cause(s)
A library that is being used in the project overrides the `margin` property of any element with `footer` class in an external CSS file.

**Comment by knmnyn** [comment]
@charlesgoh @potatowagon would you mind reviewing this PR?
