### ISSUE TITLE
Cannot select interests when registering for orbital

### ISSUE THREAD

**Issue by px1099** [nusskylab/nusskylab#587]
![image](https://user-images.githubusercontent.com/32165578/37391727-07e182b8-27a7-11e8-8528-d9021e5b7340.png)
The tags selecting boxes do not allow for selecting multiple interests (compare to the guide video).

**Comment by AZhiKai** [comment]
Hold ctrl while selecting your options, albeit I think checkboxes would be better in this scenario.

**Comment by zhaojin42** [comment]
Not sure whether there is an option to create checkboxes in the survey. =P
