### ISSUE TITLE
Cannot go back to current cohort after selecting past cohorts

### ISSUE THREAD

**Issue by lincredibleJC** [nusskylab/nusskylab#589]
Before selecting previous year's posts:
![screen shot 2018-04-07 at 8 00 08 pm](https://user-images.githubusercontent.com/22949932/38454693-6b77353e-3a9e-11e8-858f-5cec537db922.png)

After selecting previous year's posts:
![screen shot 2018-04-07 at 8 00 08 pm](https://user-images.githubusercontent.com/22949932/38454704-a68037c0-3a9e-11e8-81e7-4a486971ee12.png)

There is no button to select the current year at the bottom.

This might be related to #576

**Comment by knmnyn** [comment]
Yes, I think that is hardcoded.  Probably good to add a looping construct and better UI for that, but at the minimum add in the hard code for 2018 and current year if not shown.

I think that code snippet is featured on a few views so you may need to check whether other views can also benefit from this code update.

**Comment by chowyb** [comment]
Yes, it is hardcoded. Refer to the following:

https://github.com/nusskylab/nusskylab/blob/0ebf58ee2aac55e875fc06380890eacf62d12e54/app/controllers/cohort_helper.rb#L7-L9

I've just updated production server to include the year 2018, so the buttons for 2018 appear there now.

**Comment by knmnyn** [comment]
So, it sounds like @chowyb already solved this partially as a workaround?  Care to close?

**Comment by lincredibleJC** [comment]
Oh yes, it's fixed now.
