### ISSUE TITLE
explore the speedup of managing shared folder

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#6]
some ref: https://sethvargo.com/faster-rails-development-with-vagrant/

**Comment by Leventhan** [comment]
A lot of PayPal people are using Docker instead. There's also [Fig](http://www.fig.sh/rails.html).

**Comment by franklingu** [comment]
well, right now I am running from local machines. there is not even vagrant vms. but for deployment purpose, we will use vagrant vm for now.

**Comment by franklingu** [comment]
this is more of exploration of developers rather than task for the team.
e.g. i am not using vagrant for development now, or maybe we can explore docker later
