### ISSUE TITLE
design UI for orbital program

### ISSUE THREAD

**Issue by franklingu** [nusskylab/nusskylab#65]

**Comment by franklingu** [comment]
@knmnyn , is there any logo that I can use now? :)

**Comment by franklingu** [comment]
not important for now...

**Comment by knmnyn** [comment]
Logo?

You can try to derive some from this, or use the existing orbital ones:

https://www.google.com.sg/search?q=skylab&espv=2&biw=1440&bih=757&source=lnms&tbm=isch&sa=X&ei=OEFAVYGHLYuwuAT35YGYAw&ved=0CAYQ_AUoAQ#tbm=isch&q=skylab+size&revid=543468015&imgrc=o-VwaFNU1tFXCM%253A%3BvxTRnW-vASMBBM%3Bhttp%253A%252F%252Fhistoricspacecraft.com%252FDiagrams%252FS%252FISS_Size_Comparison_1200x700_RK2011.jpg%3Bhttp%253A%252F%252Fhistoricspacecraft.com%252Fskylab.html%3B1200%3B700

http://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Skylab_Program_Patch.png/150px-Skylab_Program_Patch.png

If you need backgrounds, I suggest that you white wash (apply some filters)
to pictures like:

http://www.astronautix.com/graphics/0/10076205.jpg

https://www.google.com.sg/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0CAYQjB0&url=http%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3ASkylab_looking_down.jpg&ei=50FAVaPXLNeTuATD2YHwDA&bvm=bv.91665533,d.c2E&psig=AFQjCNFoNBQWPH1Df8DHGoVtHxxUL31lcA&ust=1430360767490603

Sorry for the nasty looking URLs, I think you can figure it out.



Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
