### ISSUE TITLE
Replace team image if not found

### ISSUE THREAD

**Issue by yhchong** [nusskylab/nusskylab#656]
![image](https://user-images.githubusercontent.com/13570016/53139206-e3e76b80-35c3-11e9-8174-76ba85765473.png)

Replace team project image if the link is down.

**Comment by yhchong** [comment]
Current fix unable to be deployed to the production server

**Comment by zhaojin42** [comment]
Fixed via #694.

**Comment by zhaojin42** [comment]
Fixed via #694.
