### ISSUE TITLE
Privacy consent statement in registration form

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#670]
We will need a privacy consent statement in the registration form saying that they agree to let us (and our sponsors) use their personal information for contacting / tracking purposes.

**Comment by yhchong** [comment]
Add this as a question with only 1 option? 

Maybe something like...

I agree to allow the Orbital organizers (and their sponsors) to collect and use my personal information for contacting/tracking purposes. (If no, please kindly stop the registration)
- Yes
