### ISSUE TITLE
Urgent: Adviser / Peer teams are unable to view the submission to be evaluated

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#706]
This can be reproduced by viewing the Milestone submission 1 as Demo Adviser 1 / Demo Student X / Demo Student Y.

**Comment by zhaojin42** [comment]
This is likely to be related to #629.

The fix for #629 might have been too strict and it allows only the team who created the submission to view it.

**Comment by JunWei96** [comment]
Should an Adviser view/edit a submission from a team whom he/she is not responsible from?

**Comment by zhaojin42** [comment]
The adviser should only be able to view the submissions from his/her teams. I believe there is a function somewhere to consolidate all the related people for a submission. Please check if it is relevant for this issue.
