### ISSUE TITLE
Unnatural spacing in All Teams

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#726]
![image](https://user-images.githubusercontent.com/9313999/60168717-e5f25d00-9837-11e9-95b9-fd9d3ba58b41.png)

The projects in "All Teams" is meant to be in a simple grid layout but there seems to be some unnatural spacing as shown in the screenshot.

**Comment by aaditkamat** [comment]
Seems like [this is the solution to the issue](https://stackoverflow.com/questions/22866109/bootstrap-columns-not-aligning-correctly)
