### ISSUE TITLE
Editing milestone submission updates peer evaluation date

### ISSUE THREAD

**Issue by aaditkamat** [nusskylab/nusskylab#743]
One of my teams updated their Milestone 2 submission on 7th July (the submission deadline was 1st July 2359 hrs). The 'Last updated at' date for the peer evaluations for that submission updated accordingly and showed up red. This made one of the teams think that their peer evaluation was flagged out as late. The date that should be shown in that column is the date when the peer evaluation is updated and not the milestone submission. 

If we still want to show the date for milestone submission update, we can at least add a column to show the date for updating the peer evaluation and label the two columns accordingly. 

Not sure if this was an issue from before or is related to #741.

**Comment by zhaojin42** [comment]
Please refer to #736. 

There won't be any penalty on the team unless it is clear that they are doing so to "cheat" (buy time).
