### ISSUE TITLE
User Roles tab missing from user homepage

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#823]
There should be a user role tab in everyone's home page for the users to choose / switch between roles. 

Based on the rendered code from the browser, the tab is there but not visible. Please fix this soon.

Thanks!

**Comment by jjlee050** [comment]
i will take this issue. @zhaojin42 Can i ask if you prefer to switch between roles or redirect to the main panel of the roles? The latter will allow users to stay as admin while being able to access their other roles panel.

**Comment by zhaojin42** [comment]
I think the current design already does the latter by providing the links in the tab. 

There is no need for the admin to switch over to the other role.
