### ISSUE TITLE
Need a script to automatically upload videos into Youtube

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#843]
It takes a long time to manually upload the videos into Skylab now. There should be a simpler way (e.g., a script) to do so.

**Comment by durianpancakes** [comment]
https://github.com/durianpancakes/downuploader

I have not provided the set-up instructions yet, but I will do so asap.

**Comment by durianpancakes** [comment]
I have updated the guide! Please let me know if this is applicable to the issue.

**Comment by swatimahadevan** [comment]
Added solution to issue #872.
