### ISSUE TITLE
Reset password not working

### ISSUE THREAD

**Issue by yapdianhao** [nusskylab/nusskylab#857]
Reset password by entering your email gives error.
![image](https://user-images.githubusercontent.com/48383749/117120504-fe354a80-adc5-11eb-823d-5d01b3253150.png)

**Comment by yapdianhao** [comment]
Works fine on development

![image](https://user-images.githubusercontent.com/48383749/117166827-4f126680-adf9-11eb-8d26-c4c85c19f209.png)

**Comment by zhaojin42** [comment]
It could happen that the emails are not send out (and hence there is no error).

**Comment by zhaojin42** [comment]
Fixed on the deployment server by updating the credentials in the environment.
