### ISSUE TITLE
Show the team poster link and video link in the gallery for Splashdown

### ISSUE THREAD

**Issue by zhaojin42** [nusskylab/nusskylab#861]
Splashdown is likely to be an online event again.

As such, we will need to update the gallery to show the team poster link and video link eventually so that the participants could view the materials for voting.

**Comment by yapdianhao** [comment]
- [x] Backup database
- [ ] Update poster links
- [ ] Update video links

**Comment by yapdianhao** [comment]
I am planning of writing a PLPGSQL function with 2 parameters (first team, last team) so we can run the function instead of manually setting one by one.
